### ISSUE TITLE
Dependabot auto-approve job fails: GITHUB_TOKEN cannot approve PRs

### ISSUE THREAD

**Issue by heyFlorentin** [VRLYDE/saas-stack#12]
**Description:**
The Dependabot auto-approve GitHub Actions workflow is failing for PR #10 (https://github.com/VRLYDE/saas-stack/pull/10).

**Steps to Reproduce:**
1. Open or synchronize a pull request from Dependabot.
2. Wait for the "Dependabot auto-approve" GitHub Actions workflow to run.

**Observed Error:**
The job fails with the following error:
```
failed to create review: GraphQL: GitHub Actions is not permitted to approve pull requests. (addPullRequestReview)
Process completed with exit code 1.
```

**Cause:**
The default `GITHUB_TOKEN` does not have permission to approve pull requests.

**Solution:**
- Generate a Personal Access Token (PAT) with `repo` scope.
- Add it to your repository secrets (e.g., `PAT_FOR_ACTIONS`).
- Update the workflow to use this PAT instead of `GITHUB_TOKEN` for the approval step.
- Example:
  ```yaml
  env:
    PR_URL: ${{github.event.pull_request.html_url}}
    GITHUB_TOKEN: ${{secrets.PAT_FOR_ACTIONS}}
  ```
